# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^devenv/scripts/debug\.py$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:

  # Misc checks
  - id: no-commit-to-branch
    name: no commit to main or release branches
    args:
    - --branch=main
    - --pattern=^rel/
  - id: check-added-large-files
    args: ["--maxkb=50"]
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: fix-byte-order-marker

  # Check executables
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs

  # Check symlinks
  #- id: check-symlinks
  #- id: destroyed-symlinks

  # Check syntax
  - id: check-yaml
    args: [--unsafe]
  # - id: check-json
  #- id: check-toml
  #- id: check-xml

  # Fix whitespace
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]

  # Python specific checks
  - id: check-ast
  - id: check-docstring-first
  - id: requirements-txt-fixer
  - id: debug-statements
  - id: fix-encoding-pragma
    args: ["--remove"]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile=black]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args:
    - --py311-plus

- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args:
    - --max-line-length=88
    additional_dependencies:
    - flake8-broken-line==1.0.0
    - flake8-bugbear==23.9.16
    - flake8-comprehensions==3.14.0
    - flake8-debugger==4.1.2
    - flake8-logging-format==0.9.0
    - flake8-mutable==1.2.0
    - flake8-noqa==1.3.2
    - flake8-printf-formatting==1.1.2
    - flake8-unused-arguments==0.0.13
