apiVersion: dell.com/v1
kind: DevEnv
metadata:
  name: ${DEVENV_NAME}
  namespace: ${NAMESPACE}
spec:
  image: ${IMAGE}
  baseDomain: ${BASE_DOMAIN}
  authorizedKeys: ${SSH_PUB_KEYS}
  mounts:
  - kind: deployment
    mountPath: ${MOUNT_PATH}
    labels: ${LABELS}
  excludedPaths: ${EXCLUDED}
  reloadSignal: ${RELOAD_SIGNAL}
  postMountPodCmd: "${POST_MOUNT_POD_CMD}"
