apiVersion: dell.com/v1
kind: DevEnv
metadata:
  name: ${DEVENV_NAME}
  namespace: ${NAMESPACE}
spec:
  mode: ${MODE}
  port: ${PORT}
  image: ${IMAGE}
  baseDomain: ${BASE_DOMAIN}
  albGroupName: ${GROUP_NAME}
  authorizedKeys: ${SSH_PUB_KEYS}
  mounts: ${MOUNTS}
  excludedPaths: ${EXCLUDED}
  reloadSignal: ${RELOAD_SIGNAL}
  postMountPodCmd: "${POST_MOUNT_POD_CMD}"
