apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remote-dev-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remote-dev-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: remote-dev-operator-account
    namespace: {{ $.Release.Namespace }}
