apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remote-dev-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [namespaces]
    namespaces: ["*"]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [serviceaccounts]
    namespaces: ["*"]
    verbs: [list, watch, get, create, patch]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [roles]
    namespaces: ["*"]
    verbs: [list, watch, get, create, patch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [dell.com]
    resources: [devenvs]
    verbs: [list, watch, patch, get]

  - apiGroups: [""]
    resources: [events]
    verbs: [create, list, watch]

  # TODO: Restrict after restricting operator/role.yaml perms
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
