apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remote-dev-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remote-dev-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: remote-dev-operator-account
