apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devenvs.dell.com
spec:
  scope: Namespaced
  group: dell.com
  names:
    kind: DevEnv
    plural: devenvs
    singular: devenv
    shortNames:
    - devenv
    - de
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - image
            - authorizedKeys
            - baseDomain
            properties:
              image:
                type: string
                description: The container image of the environment.
                default: 702886132326.dkr.ecr.eu-west-1.amazonaws.com/devenv:latest
              authorizedKeys:
                type: array
                description: A list of SSH keys to authorize for SSH access to environment.
                minItems: 1
                items:
                  type: string
                  description: A public SSH key to add to the env's SSH server.
              pvcSize:
                type: string
                description: Size of shared PVC to use for mounting of code.
                default: 8Gi
              baseDomain:
                type: string
                description: Base domain name under which subdomains will be created for every environment.
              mounts:
                type: array
                description: A list of labels that select specific Deployments or Statefulsets along with a path to mount the PVC that contains the code or binary.
                default: []
                items:
                  type: object
                  properties:
                    kind:
                      type: string
                      description: The kind of target resource
                      enum:
                      - deployment
                      - statefulset
                    mountPath:
                      type: string
                      description: The path the PVC should be mounted on
                    labels:
                      type: object
                      description: The labels that have been assigned to target Deployment or Statefulset
                      additionalProperties:
                        type: string
              excludedPaths:
                type: array
                description: Code paths to be excluded from rsync
                items:
                  type: string
                default:
                - ".git"
                - ".vscode"
                - "__pycache__"
                - ".pyc"
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
