apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      serviceAccountName: {name}
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: {name}
      containers:
      - name: {name}
        image: {image}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /home/docker/code
          name: code
          securityContext:
            fsGroup: 1000
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        env:
        - name: authorized_keys
          value: {ssh_keys!r}
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
