apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      serviceAccountName: {name}
      terminationGracePeriodSeconds: 5
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: {name}
      containers:
      - name: {name}
        image: {image}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/docker/code
          name: code
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        env:
        - name: authorized_keys
          value: {ssh_keys!r}
        - name: mounts
          value: "{mounts}"
        - name: envname
          value: {name}
        - name: reload_signal
          value: {reload_signal}
        - name: post_mount_pod_cmd
          value: {post_mount_pod_cmd}
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m
