apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {name}
  labels:
    app: {name}
subjects:
- kind: ServiceAccount
  name: {name}
roleRef:
  kind: Role
  name: {name}
  apiGroup: rbac.authorization.k8s.io
